### ISSUE TITLE
GreedySelector can not be serialized with pickle

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/scikit-cosmo#99]
I'm using [pickle](https://docs.python.org/3/library/pickle.html) to save the full state of a model to the disk and load it later. 

Unfortunately `GreedySelector` does not currently support pickle:

```py
from skcosmo.feature_selection import FPS
import pickle

fps = FPS(n_features_to_select=23)

# ... do stuff ...

with open("saved-fps.pickle", "wb") as fd:
    pickle.dump(fps, fd)
```

This results in 

```
Traceback (most recent call last):
  File "pickle-test.py", line 9, in <module>
    pickle.dump(fps, fd)
AttributeError: Can't pickle local object 'GreedySelector.__init__.<locals>.<lambda>'
```

I think we should add support for pickle since it is a tool commonly used for Python projects. 

----

We should also check that all other classes support being serialized with pickle. If needed, we can customize the code used to save/load a given class: https://docs.python.org/3/library/pickle.html#pickle-inst

**Comment by rosecers** [comment]
Only lambda statement is progress bar in line 134, easy fix.
